version: '3.8'

services:
  # Base de données MongoDB commune pour le développement
  mongodb:
    image: mongo:latest
    container_name: gatcha-mongodb-auth
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db-auth
    restart: always

volumes:
  mongo_data: